import { defineConfig } from "tsdown"

const packages = {
	core: [
		"Api",
		"Capability",
		"Deployment",
		"Convert",
		"Generation",
		"GenerationProcess",
		"GenerationSchema",
		"Hooks",
		"HttpApi",
		"Identifier",
		"Plugin",
		"PluginContributions",
		"Persistence",
		"Policies",
		"ProviderContract",
		"Registry",
		"Provider",
		"Router",
		"Route",
		"Routing",
		"RoutingProcess",
		"RoutingRuntime",
	],
	"provider-openai": [
		"OpenAIResponses",
		"OpenAIChatCompletions",
		"Deployment",
		"GenerationAssembler",
	],
	"provider-anthropic": ["AnthropicMessages", "Deployment", "GenerationAssembler"],
	"plugin-openai-responses": ["OpenAIResponsesPlugin"],
	"plugin-openai-chat-completions": ["OpenAIChatCompletionsPlugin"],
	"plugin-anthropic-messages": ["AnthropicMessagesPlugin"],
	"protocol-openai-responses": [
		"Api",
		"Convert",
		"Http",
		"OpenAIResponsesSchema",
		"OpenResponses",
	],
	"protocol-openai-chat-completions": ["Api", "Convert", "Http"],
	"protocol-anthropic-messages": ["Api", "Convert", "Http"],
	"effect-ai": ["EffectAI"],
	"persistence-sql": ["PersistenceSql"],
}

export default defineConfig(
	Object.entries(packages).map(([name, modules]) => ({
		name,
		cwd: `packages/${name}`,
		entry: {
			index: "src/index.ts",
			...Object.fromEntries(modules.map((module) => [module, `src/${module}.ts`])),
		},
		format: "esm",
		platform: "neutral",
		target: "es2022",
		fixedExtension: true,
		dts: true,
		sourcemap: true,
		deps: { neverBundle: ["effect", "@better-router/core"] },
	})),
)
